#services:
#  mongodb:
#    image: mongo
#    container_name: mongo_db
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongo: /data/db
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=santho
#      - MONGO_INITDB_ROOT_PASSWORD=santho
#  mongoexpress:
#    image: mongo-express
#    container_name: mongo_express
#    restart: always
#    ports:
#      - "8081:8081"
#    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=santho
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=santho
#      - ME_CONFIG_MONGODB_SERVER = mongodb
#volumes:
#  mongo:
services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=santho
      - MONGO_INITDB_ROOT_PASSWORD=santho

  mongoexpress:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=mongo
      - ME_CONFIG_BASICAUTH_PASSWORD=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=santho
      - ME_CONFIG_MONGODB_ADMINPASSWORD=santho
      - ME_CONFIG_MONGODB_SERVER=mongodb

volumes:
  mongo:
